"""Ajout de la table NewBeeImage

Revision ID: 09b946ed8dbc
Revises: 1dab97d04a83
Create Date: 2025-03-25 14:05:25.814299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b946ed8dbc'
down_revision = '1dab97d04a83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_bee_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_name', sa.String(length=255), nullable=False),
    sa.Column('image_data', sa.LargeBinary(), nullable=False),
    sa.Column('has_varroa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('new_bee_image')
    # ### end Alembic commands ###
